"""empty message

Revision ID: 16fc72635833
Revises: 87846a8c542f
Create Date: 2025-10-08 04:19:20.507529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '16fc72635833'
down_revision: Union[str, Sequence[str], None] = '87846a8c542f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_stock', sa.Integer(), nullable=True))
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'stocks', ['id_stock'], ['id_stock'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id_stock')

    # ### end Alembic commands ###
