"""empty message

Revision ID: 337001f0eae6
Revises: eb1bdec1ce5c
Create Date: 2025-08-31 04:19:14.568016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '337001f0eae6'
down_revision: Union[str, Sequence[str], None] = 'eb1bdec1ce5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
