"""empty message

Revision ID: 3db7ce493a04
Revises: efe97631af21
Create Date: 2025-09-02 19:46:14.315963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3db7ce493a04'
down_revision: Union[str, Sequence[str], None] = 'efe97631af21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id_consulta', sa.INTEGER(), nullable=False),
    sa.Column('pregunta', sa.VARCHAR(), nullable=False),
    sa.Column('respuesta', sa.VARCHAR(), nullable=True),
    sa.Column('id_gerente', sa.INTEGER(), nullable=True),
    sa.Column('id_users', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_gerente'], ['gerentes.id_gerente'], ),
    sa.ForeignKeyConstraint(['id_users'], ['users.id_users'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###
