"""empty message

Revision ID: 421f49f17d3a
Revises: 3db7ce493a04
Create Date: 2025-09-15 17:21:42.723826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '421f49f17d3a'
down_revision: Union[str, Sequence[str], None] = '3db7ce493a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_users', sa.Integer(), nullable=False),
    sa.Column('id_gerente', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    # ### end Alembic commands ###
