"""empty message

Revision ID: 87846a8c542f
Revises: cb581cfd6b87
Create Date: 2025-10-08 04:07:00.534641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '87846a8c542f'
down_revision: Union[str, Sequence[str], None] = 'cb581cfd6b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gerentes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('productos_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('id_stock')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_stock', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('productos_ibfk_1'), 'stocks', ['id_stock'], ['id_stock'])
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('gerentes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
