"""empty message

Revision ID: e60ac099152d
Revises: 
Create Date: 2025-08-31 03:09:38.260398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e60ac099152d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerentes',
    sa.Column('id_gerente', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrasenia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_gerente')
    )
    op.create_table('stocks',
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_stock')
    )
    op.create_table('users',
    sa.Column('id_users', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrasena', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_users')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Numeric(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('talle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)

    op.create_table('carritos',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_users', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_users'], ['users.id_users'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carritos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))

    op.drop_table('productos')
    op.drop_table('users')
    op.drop_table('stocks')
    op.drop_table('gerentes')
    # ### end Alembic commands ###
