"""empty message

Revision ID: eb1bdec1ce5c
Revises: e60ac099152d
Create Date: 2025-08-31 03:48:43.754065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'eb1bdec1ce5c'
down_revision: Union[str, Sequence[str], None] = 'e60ac099152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
