"""empty message

Revision ID: efe97631af21
Revises: 337001f0eae6
Create Date: 2025-09-02 19:19:04.347907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'efe97631af21'
down_revision: Union[str, Sequence[str], None] = '337001f0eae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_gerente', sa.Integer(), nullable=True),
    sa.Column('id_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_gerente'], ['gerentes.id_gerente'], ),
    sa.ForeignKeyConstraint(['id_users'], ['users.id_users'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    # ### end Alembic commands ###
